application: auto-repair-shop
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /
  script: dermico.py
    
- url: /index\.html
  script: dermico.py
    
- url: /Customer
  script: dermico.py
    
- url: /Search
  script: dermico.py
    
    